### ISSUE TITLE
What's the "globalRequest" object on the docs?

### ISSUE THREAD

**Issue by anaibol** [sendgrid/nodejs-http-client#1]
```javascript
var Client = require('sendgrid-rest').Client
var emptyRequest = require('sendgrid-rest').request
var client = new Client(globalRequest)
var request = JSON.parse(JSON.stringify(emptyRequest))
```

**Comment by thinkingserious** [comment]
Apologies, that should not have been there in the README.

I was using that object to demonstrate adding global [request object](https://github.com/sendgrid/nodejs-http-client/blob/master/lib/client.js#L8) settings, however, I failed to actually set the globalRequest object in the README. You can see it in use [here](https://github.com/sendgrid/nodejs-http-client/blob/master/examples/example.js#L9). 

For example, say you wanted to have a particular header added to all of your calls. In that case you would set the header when you instantiate your `Client` object, same with any other request setting.

Thanks for catching this, I've already updated the README.

**Comment by anaibol** [comment]
Great thanks!
