### ISSUE TITLE
Demonstrate how to review the request body for troubleshooting

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/nodejs-http-client#13]
When debugging, it can be useful to examine the request body before sending to the SendGrid API.

Prove an example of how to examine the request body in TROUBLESHOOTING.md. For an example, see [here](https://github.com/sendgrid/sendgrid-python/blob/master/TROUBLESHOOTING.md#request-body).

**Comment by TunedMidja** [comment]
I was going to take on this one but is a little confused with what needs to be done, especially after looking at the Python HTTP client: https://github.com/sendgrid/python-http-client/blob/master/TROUBLESHOOTING.md
it shows how to examine the response body, not the request body (but it uses the word request in one place).
Could you please clarify?

**Comment by mukulmishra18** [comment]
I am working on it. Thanks.
