### ISSUE TITLE
Problems with accents ( áéíóúÑñ ) JSON body

### ISSUE THREAD

**Issue by eaparango** [sendgrid/nodejs-http-client#2]
Automatically add Content-Type: application/json when there is a request body.

Should be: **Content-Type: application/json; charset=utf-8**

**Comment by thinkingserious** [comment]
@eaparango great catch and thanks for posting the solution!

We'll get this fixed.

**Comment by eaparango** [comment]
I can not send email when there are accents!!
is the email client or server REST?

PD: name user have accents.

this is my JSON:
 {
 "from": {
    "email": "no-reply@fracttal.com",
    "name": "Fracttal"
  },
  "personalizations": [
    {
      "to": [
        {
          "email": "xxx@ejemplo",
          "name": "áéíóúÑñ"
        }
      ]
    }
  ],
  "subject": "Hello",
  "content": [
    {
      "type": "text/plain",
      "value": "Hello"
    }
  ]
}

**Comment by eaparango** [comment]
I change the local library, but fails to send mail. I have my service down. this is serious!!

{ "Errors": [{ "message": "Bad Request", "field": null, "help": null}]}

{Server: 'nginx'
   date: 'Wed, 16:14:22 GMT June 15, 2016'
   'Content-type' 'application / json'
   'Content-length' '63',
   connection: 'close'
   'X-frame-options' 'DENY'}

**Comment by thinkingserious** [comment]
Hello @eaparango,

I'll be taking a look at this.

BTW, this is not the SendGrid API client, here it is: https://github.com/sendgrid/sendgrid-nodejs

**Comment by eaparango** [comment]
From there come I'm trying to see because I can not send email when you have accents, I thought it was this mistake but I think it is the server that does not accept UTF-8

**Comment by thinkingserious** [comment]
Cool, thanks for clarifying.

**Comment by thinkingserious** [comment]
Should be fixed with version 2.2.1
