### ISSUE TITLE
Update Travis.yml to use supported node versions

### ISSUE THREAD

**Issue by mbernier** [sendgrid/nodejs-http-client#21]
#### Issue Summary

The nodeJS releases site shows that .10 and .12 are no longer supported. They also show some major builds that are supported. Please update Travis.yml accordingly.

Example: https://github.com/sendgrid/smtpapi-nodejs/pull/37

**Comment by mbernier** [comment]
@rasjani would you be up for making a PR against our repo for that change? We'd love to give you credit!!

**Comment by rasjani** [comment]
I actually did - before i noticed https://github.com/sendgrid/nodejs-http-client/pull/22 which was essentially the same patch but from different author =)
