### ISSUE TITLE
Support maxSockets

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/nodejs-http-client#3]
#### Issue Summary

See https://github.com/sendgrid/sendgrid-nodejs/issues/270
#### Technical details:
- node-http-client Version: 2.X
- Node.js Version: 4.1.2

**Comment by yanosh-igor** [comment]
It will be very useful feature. Waiting for it..

**Comment by jaydp17** [comment]
@thinkingserious  looks like you are no longer using https://github.com/sendgrid/nodejs-http-client in https://github.com/sendgrid/sendgrid-nodejs.

**Comment by thinkingserious** [comment]
That's correct @jaydp17.

**Comment by valtlfelipe** [comment]
I believe this has already been implemented in https://github.com/sendgrid/nodejs-http-client/pull/15. 

Or is this issue related to implement it on https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/client ? If yes, I can take it.

**Comment by valtlfelipe** [comment]
I createt a PR at https://github.com/sendgrid/sendgrid-nodejs/pull/837 to support maxSockets on the mail package.

**Comment by childish-sambino** [comment]
Closing all open issues and PRs. This repo is no longer maintained. Please use https://github.com/sendgrid/sendgrid-nodejs/tree/master/packages/client instead.
