### ISSUE TITLE
We all need a little help, sometimes. Add a Troubleshooting file

### ISSUE THREAD

**Issue by mbernier** [sendgrid/nodejs-http-client#38]
#### Issue Summary

Borrow the file from [sendgrid-nodejs](https://github.com/sendgrid/sendgrid-nodejs/blob/master/TROUBLESHOOTING.md) and modify it to fit this repo! 

Please make sure you show how to output the SMTPAPI header

**Comment by JSmurf** [comment]
I can work on this!

**Comment by thinkingserious** [comment]
Thank you @JSmurf!

**Comment by valerianpereira** [comment]
Looks like this is done already.

**Comment by childish-sambino** [comment]
Closing all open issues and PRs. This repo is no longer maintained. Please use https://github.com/sendgrid/sendgrid-nodejs/tree/master/packages/client instead.
