### ISSUE TITLE
Improve esdoc's coverage report

### ISSUE THREAD

**Issue by mbernier** [sendgrid/nodejs-http-client#43]
#### Issue Summary

Adding documentation is a great way to save yourself and other developers time when they are looking at code to understand what was coded or when they are troubleshooting an issue. 

#### Steps to Reproduce

1. clone this repo `git clone https://github.com/sendgrid/nodejs-http-client.git`
2. run `npm install`
  a. If #42 is not complete or merged yet, `npm i chai@2.3.0 esdoc esdoc-coverage-plugin`
3. run `./node_modules/.bin/esdoc`
4. Open the coverage.json file that was generated in the docs directory
5. Find files that need more docs coverage and add it in!

**Comment by kburk1997** [comment]
If no one else has claimed this yet, I'd be willing to take this on

**Comment by childish-sambino** [comment]
Closing all open issues and PRs. This repo is no longer maintained. Please use https://github.com/sendgrid/sendgrid-nodejs/tree/master/packages/client instead.
