### ISSUE TITLE
idiomatic changes needed, as reported by CodeClimate

### ISSUE THREAD

**Issue by mbernier** [sendgrid/nodejs-http-client#49]
#### Issue Summary

CodeClimate is watching our repo and has reported some specific changes to the code, can you please fix these up?

https://codeclimate.com/github/sendgrid/nodejs-http-client/pull/48

**Comment by viniciuskneves** [comment]
Seems like CodeClimate is offline. Do you have a print screen or something like that?

**Comment by mithunsasidharan** [comment]
@mbernier : https://github.com/sendgrid/nodejs-http-client/pull/61 Please review the PR for this issue !
