### ISSUE TITLE
Assert file exists

### ISSUE THREAD

**Issue by mbernier** [sendgrid/nodejs-http-client#57]
#### Issue Summary

@mptap I am curious if you would be interested in switching these if statements over to test assertions? https://github.com/sendgrid/nodejs-http-client/blob/master/test/test.js 

I really like how the tests you created in https://github.com/sendgrid/smtpapi-nodejs/pull/60 ended up displaying in Travis. That would be amazing to have here too.

**Comment by mptap** [comment]
@mbernier: Sure thing, on it!

**Comment by mbernier** [comment]
Ohhhh yeah!! Thank you!
