### ISSUE TITLE
Fix "guard-for-in" issue in lib/client.js

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/nodejs-http-client#66]
The body of a for-in should be wrapped in an if statement to filter unwanted properties from the prototype.

https://codeclimate.com/github/sendgrid/nodejs-http-client/lib/client.js#issue_59f5551205f9300001000021

**Comment by mslourens** [comment]
Fixed with PR #72

**Comment by childish-sambino** [comment]
Closing all open issues and PRs. This repo is no longer maintained. Please use https://github.com/sendgrid/sendgrid-nodejs/tree/master/packages/client instead.
