### ISSUE TITLE
Fix "comma-dangle" issue in lib/client.js

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/nodejs-http-client#68]
Unexpected trailing comma.

https://codeclimate.com/github/sendgrid/nodejs-http-client/lib/client.js#issue_59f5551205f9300001000025

**Comment by mslourens** [comment]
Fixed with PR #70

**Comment by childish-sambino** [comment]
Fixed by https://github.com/sendgrid/nodejs-http-client/pull/61
