### ISSUE TITLE
Add CodeCov support to .travis.yml

### ISSUE THREAD

**Issue by mbernier** [sendgrid/nodejs-http-client#74]
Issue Summary

Add this to our travis.ci configuration so that code coverage tests will run!
https://github.com/codecov/example-node/blob/master/.travis.yml

**Comment by childish-sambino** [comment]
Closing all open issues and PRs. This repo is no longer maintained. Please use https://github.com/sendgrid/sendgrid-nodejs/tree/master/packages/client instead.
