### ISSUE TITLE
Remove marked security vulnerability

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/nodejs-http-client#86]
#### Issue Summary

Reported by GitHub:

Known moderate severity security vulnerability detected in marked < 0.3.7 defined in package-lock.json.

package-lock.json update suggested: marked ~> 0.3.7.

**Comment by robincher** [comment]
Hi, i think this happened due esdoc still refereing to a vulnerable (marked) sub dependency.

https://snyk.io/test/github/esdoc/esdoc?severity=high&severity=medium&severity=low

**Comment by thinkingserious** [comment]
Thanks for the additional information @robincher!

**Comment by robincher** [comment]
small thing, i got the same alert too, and somehow ended up here hehe :).

**Comment by robincher** [comment]
Fixes in PR #87

**Comment by robincher** [comment]
Can put this as an hacktoberfest label ? @thinkingserious  :)

**Comment by thinkingserious** [comment]
Hi @robincher,

Please see https://github.com/sendgrid/nodejs-http-client/pull/117, thanks!
