### ISSUE TITLE
Implement auto-deploy to package manager

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/nodejs-http-client#90]
#### Issue Summary

When all tests on the master branch pass in Travis CI, we would like to auto-deploy the release to the package manager.

Before writing any code, we suggest you review our `CONTRIBUTING.md` file and propose your solution for discussion here in the comments. Thank you!

#### Aceptance Criteria

* when Travis CI passes all tests on the master branch we auto-deploy to the package manager
* the version is determined by the `CHANGELOG.md`

**Comment by mauricetmeyer** [comment]
@thinkingserious I would really like to look into this, later today.

**Comment by mauricetmeyer** [comment]
@thinkingserious I've never really worked with travis, but after reading the docs for a bit my solution would work like the following.

- [before_deploy:](
https://docs.travis-ci.com/user/deployment/npm/#running-commands-before-and-after-deploy) Will run a nodejs script reading ```CHANGELOG.md``` that will then call ```npm version``` to bump the version.
- deploy: Uses the [NPM Provider](https://docs.travis-ci.com/user/deployment/npm/) to publish to npm when a push to master happens.

**Comment by childish-sambino** [comment]
Closing as we're now using internal tooling for this.
