### ISSUE TITLE
Require conformance to style standards

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/nodejs-http-client#92]
#### Issue Summary

In the `CONTRIBUTING.md` file there is a section on Style Guidelines & Naming Conventions. Please review and implement a check in Travis CI. If there are any style errors, either fix or create a rule to exclude the error.

Before writing any code, we suggest you review our `CONTRIBUTING.md` file and propose your solution for discussion here in the comments. Thank you!

#### Aceptance Criteria

* TravisCI checks that the code conforms to our Style Guidelines & Naming Conventions as defined in our `CONTRIBUTING.md` file
* tests pass locally, in Travis CI and using Docker

**Comment by ofaltins** [comment]
I'd like to look into this.

I've reviewed the Style Guidelines & Naming Conventions section which specifies that contributors should get a pass from ESLint with the standard styleguide. 

Additionally, there's the unofficial styleguide which in turn provides an [eslint.rc file](https://github.com/felixge/node-style-guide/blob/master/.eslintrc) which can/should take precedence over the standard styleguide if there are any conflicts (TBD?)

If there are a lot of discrepancies between the new eslint.rc file and existing code base, i'd like to circle back to get some guidance on how to proceed.

Once the "final" eslint.rc file is defined, i'd add a lint script in package.json, and add npm run lint in the script section in travis.yml.

Let me know if this is in accordance with your expectations.

**Comment by childish-sambino** [comment]
Closing all open issues and PRs. This repo is no longer maintained. Please use https://github.com/sendgrid/sendgrid-nodejs/tree/master/packages/client instead.
