### ISSUE TITLE
Security vulnerability for mocha@2.4.5 

### ISSUE THREAD

**Issue by robincher** [sendgrid/nodejs-http-client#94]
#### Issue Summary

There are security vulnerabilities found in mocha@2.4.5 sub-dependencies. The vulnerabilities found are marked as **High-severity**, so i thought it should bring this up for the team consideration since it will be a pretty straight-forward fix. The recommended fix is to upgrade mocha to version 4 (minimum)

Expected work to be done
1. Update Mocha to version 4 (or 5) in package.json
2. Update travis.yml to ensure travis only run up to node version supported by Mocha version 4 (or 5 the latest)

#### Steps to Reproduce

1. npm install 
2. npm audit
3. Analyse the output.

**More information for the vulnerability :** 
https://snyk.io/test/npm/mocha/2.4.5

#### Technical details:

* node-http-client Version: master (latest commit: [a341cf3083b193f0117f91ed6070d0b02c0ba241])
* Node.js Version:8.x.x

**Comment by robincher** [comment]
@thinkingserious  I can take this piece of work if you think it's worthwhile for this month :)

**Comment by thinkingserious** [comment]
Thank you @robincher!
