### ISSUE TITLE
Run our *.md documents in this repo through the Grammer.ly service and update

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/nodejs-http-client#95]
#### Issue Summary

We would like to get our English polished up throughout the repo.

#### Aceptance Criteria

* Every .md file in this repo has been run through the Grammer.ly service and updated accordingly

**Comment by ays14** [comment]
I'm on it. Please assign it to me @thinkingserious

**Comment by thinkingserious** [comment]
Thank you @ays14, it's all yours!

**Comment by ays14** [comment]
@thinkingserious are the other two tasks as listed in the PR comment relevant to this issue. I thought they are not because of the two tasks were related to code so I did not check them. Is it fine? Please let me know if I missed something or did something wrong.

**Comment by childish-sambino** [comment]
Closing all open issues and PRs. This repo is no longer maintained. Please use https://github.com/sendgrid/sendgrid-nodejs/tree/master/packages/client instead.
